FROM node:alpine3.11

# Install Shadow non busybox for better user management & support
RUN apk add --no-cache git python3 build-base openssl-dev

# Add Sudo to allow occasional usage of root. I wish I could remove this but I can't seem to get the node_modules volume working correctly.
RUN apk add --no-cache sudo \
	&& echo node ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/node \
	&& chmod 0440 /etc/sudoers.d/node


ENV GLIBC_VERSION '2.31-r0'

RUN wget -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
	&& wget -O glibc.apk "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk" \
	&& wget -O glibc-bin.apk "https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk" \
	&& apk add glibc-bin.apk glibc.apk \
	&& /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib \
	&& echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf \
	&& rm -rf glibc.apk glibc-bin.apk /var/cache/apk/*

CMD [ "tail", "-f", "/dev/null" ]