version: '3.7'

volumes:
  apiModules:
  databaseData:

networks:
  internalDB:

services:
  API:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: kristianfoss/development/type-graphql-prisma-lab:api
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - internalDB
    environment:
      DB_HOST: 'Database'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'password'
    volumes:
      - ./:/workspace:delegated
      - apiModules:/workspace/node_modules

  Database:
    image: postgres:alpine
    volumes:
      - databaseData:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - internalDB
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: typegql-prisma
